/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle.groovy

import org.gradle.tooling.GradleConnector
import org.gradle.tooling.model.idea.IdeaDependency
import org.gradle.tooling.model.idea.IdeaModule
import org.gradle.tooling.model.idea.IdeaProject

class App {
    static void main(String[] args) {
        def connection = GradleConnector.newConnector()
            .forProjectDirectory(new File("app"))
            .connect()

        IdeaProject build = connection.model(IdeaProject.class).get()
        build.modules.each { IdeaModule module ->
            println "Project $module.name:"
            module.dependencies.each { IdeaDependency dep ->
                println dep
            }
        }

        connection.close()
    }
}
